import steel_toolbox.steel_tools as st
import steel_toolbox.lab_tools as lt

sp1 = st.PolygonalColumn.from_slenderness_and_thickness(16, 30., 3., 700., 700., 'fcA')
sp2 = st.PolygonalColumn.from_slenderness_and_thickness(16, 40., 3., 700., 700., 'fcA')
sp3 = st.PolygonalColumn.from_slenderness_and_thickness(16, 50., 3., 700., 700., 'fcA')
sp4 = st.PolygonalColumn.from_slenderness_and_thickness(20, 30., 3., 700., 700., 'fcA')
sp5 = st.PolygonalColumn.from_slenderness_and_thickness(20, 40., 3., 700., 700., 'fcA')
sp6 = st.PolygonalColumn.from_slenderness_and_thickness(20, 50., 2., 700., 700., 'fcA')
sp7 = st.PolygonalColumn.from_slenderness_and_thickness(24, 30., 3., 700., 700., 'fcA')
sp8 = st.PolygonalColumn.from_slenderness_and_thickness(24, 40., 2., 700., 700., 'fcA')
sp9 = st.PolygonalColumn.from_slenderness_and_thickness(24, 50., 2., 700., 700., 'fcA')

sp1.experiment = lt.Experiment.from_file('../data/experiments/sample_1.asc')
sp2.experiment = lt.Experiment.from_file('../data/experiments/sample_2_all_data_appended.asc')
sp3.experiment = lt.Experiment.from_file('../data/experiments/sample_3_realtest.asc')
sp4.experiment = lt.Experiment.from_file('../data/experiments/sample_4_realtest.asc')
sp5.experiment = lt.Experiment.from_file('../data/experiments/sample_5_realtest.asc')
sp6.experiment = lt.Experiment.from_file('../data/experiments/sample_6_realtest.asc')
sp7.experiment = lt.Experiment.from_file('../data/experiments/sample_7_realtest.asc')
sp8.experiment = lt.Experiment.from_file('../data/experiments/sample_8_realtest.asc')
sp9.experiment = lt.Experiment.from_file('../data/experiments/sample_9_realtest.asc')
#sp1.test.add_eccentricity(sp1.test, 'x', ['FTG1', "FTG5"], sp1.cs_properties.moi_xx, sp1.min_dist, sp1.thickness, 210000)

# Load 3D scans
sp1.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp1_1_initial.stl')
sp2.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp2_1_initial.stl')
sp3.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp3_1_initial.stl')
sp4.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp4_1_initial.stl')
sp5.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp5_1_initial.stl')
sp6.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp6_1_initial.stl')
sp7.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp7_1_initial.stl')
sp8.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp8_1_initial.stl')
sp9.scan_initial = lt.Scan3D.from_stl_file('../data/stl/sp9_1_initial.stl')

sp1.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp1_1_deformed.stl')
sp2.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp2_1_deformed.stl')
sp3.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp3_1_deformed.stl')
sp4.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp4_1_deformed.stl')
sp5.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp5_1_deformed.stl')
sp6.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp6_1_deformed.stl')
sp7.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp7_1_deformed.stl')
sp8.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp8_1_deformed.stl')
sp9.scan_deformed = lt.Scan3D.from_stl_file('../data/stl/sp9_1_deformed.stl')

# figure = plt.figure()
# axes = mplot3d.Axes3D(figure)
# axes.add_collection3d(mplot3d.art3d.Poly3DCollection(sp1.scan.vectors))
# scale = sp1.scan.points.flatten(-1)
# axes.auto_scale_xyz(scale, scale, scale)
# plt.show()
